import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Window } from "../components/Window";
import { File } from "../components/File";
import { useEffect, useState } from "react";
import { Task } from "../components/Task";
import CmdElement from "../components/elements/Console";
import ReadMeElement from "../components/elements/ReadMe";
import { UniversalProvider } from "../components/utils/UniversalProvider";
import { DesktopElement } from "../components/utils/Element";
import MinesweeperElement from "../components/elements/Minesweeper";
import FaicampElement from "../components/elements/Faicamp";

export default function Home() {
  const [elements, setElements] = useState<DesktopElement[]>([
    ReadMeElement,
    CmdElement,
    MinesweeperElement,
    FaicampElement,
  ]);

  const handleWindowZ = (index: number): void => {
    elements.forEach((el) => {
      el.file.windowRef.current?.decrementZIndex();
    });

    elements[index].file.windowRef.current?.setZIndex(99 + elements.length);
  };

  const handleTaskPosition = (index: number): void => {
    let els = [...elements];

    els.forEach((el) => {
      el.task.position! -= 1;
    });

    els[index].task.position! = elements.length;
    setElements(els);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </Head>
      <main className={styles.main}>
        <div className={styles.desktop}>
          <div className={styles.desktop_icons}>
            {elements
              ? elements!.map((element) => (
                  <File
                    key={1}
                    windowRef={element.file.windowRef}
                    name={element.file.name}
                    icon={element.window.icon}
                  />
                ))
              : null}
          </div>
          <div className={styles.desktop_windows}>
            {elements
              ? elements!.map((element) => (
                  <UniversalProvider key={element.task.id}>
                    <Window
                      title={element.window.title}
                      icon={element.window.icon}
                      taskRef={element.window.taskRef}
                      ref={element.file.windowRef}
                      zIndex={100 + elements.indexOf(element)}
                      onWindowGrab={handleWindowZ}
                      onWindowOpen={handleTaskPosition}
                      resizable={element.window.resizable}
                      allowFullscreen={element.window.allowFullscreen}
                      width={element.window.width}
                      height={element.window.height}
                    >
                      {element.window.children}
                    </Window>
                  </UniversalProvider>
                ))
              : null}
          </div>
        </div>
        <div className={styles.taskbar}>
          {elements
            ? [...elements]
                .sort((elA, elB): number => {
                  let elApos = elA.task.position!;
                  let elBpos = elB.task.position!;
                  if (elApos < elBpos) return -1;
                  if (elApos > elBpos) return 1;
                  return 0;
                })
                .map((element) => {
                  const index = elements.indexOf(element);
                  return (
                    <Task
                      key={index}
                      windowRef={element.file.windowRef}
                      name={element.file.name}
                      icon={element.window.icon}
                      ref={element.window.taskRef}
                      id={index}
                      position={
                        element.task.position ? element.task.position : index
                      }
                    />
                  );
                })
            : null}
        </div>
      </main>
    </div>
  );
}
